name = "line-translator"
main = "src/index.js"
compatibility_date = "2024-01-01"
routes = [
  { pattern = "line-translator.siwu-translation.workers.dev", zone_name = "siwu-translation.workers.dev" }
]
